const patterns = Object.fromEntries(new Map([
	["Enseigne", "^[0-9A-Z]{2}[0-9A-Z]{6}$"],
	["ModeCol", "^(CCC|CDR|CDS|REL)$"],
	["ModeLiv", "^(LCC|24R|24L)$"],
	["NDossier", "^(|[0-9A-Z_ -]{0,15})$"],
	["NClient", "^(|[0-9A-Z]{0,9})$"],
	["Ville", "^[A-Za-z_\\-' ]{2,25}$"],
	["Pays", "^[A-Za-z]{2}$"],
	["Latitude", "^-?[0-9]{2}\\.[0-9]{7}$"],
	["Longitude", "^-?[0-9]{2}\\.[0-9]{7}$"],
	["DelaiEnvoi", "^-?([0-9]{2})$"],
	["RayonRecherche", "^[0-9]{1,4}$"],
	["NumPointRelais", "^[0-9]{6}$"],
	["TypeActivite", "^(\\d{3},|\\d{3})*$"],
	["Expe_Langage", "^[A-Z]{2}$"],
	["Expe_Ad1", "^[0-9A-Z_\\-'., /]{2,32}$"],
	["Expe_Ad2", "^[0-9A-Z_\\-'., /]{2,32}$"],
	["Expe_Ad3", "^[0-9A-Z_\\-'., /]{2,32}$"],
	["Expe_Ad4", "^[0-9A-Z_\\-'., /]{2,32}$"],
	["Expe_Ville", "^[A-Z_\\-' ]{2,26}$"],
	["Expe_CP", "^[0-9@]{1}[0-9]{4}$"],
	["Expe_Pays", "^[A-Z]{2}$"],
	["Expe_Tel1", "^((00|\\+)33|0)[0-9][0-9]{8}$"],
	["Expe_Tel2", "^((00|\\+)33|0)[0-9][0-9]{8}$"],
	["Expe_Mail", "^[0-9a-zA-Z!#$%&'*+/=?^_`{|}~-]+((\\.[a-zAZ0-9!#$%&'*+/=?^_`{|}~-]+)?)+@(?:[a-zAZ0-9](?:[a-zA-Z0-9-_]*[a-zA-Z0-9])?\\.)+[azA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?$"],
	["Dest_Langage", "^[A-Z]{2}$"],
	["Dest_Ad1", "^[0-9A-Z_\\-'., /]{2,32}$"],
	["Dest_Ad2", "^[0-9A-Z_\\-'., /]{2,32}$"],
	["Dest_Ad3", "^[0-9A-Z_\\-'., /]{2,32}$"],
	["Dest_Ad4", "^[0-9A-Z_\\-'., /]{2,32}$"],
	["Dest_Ville", "^[A-Z_\\-' ]{2,26}$"],
	["Dest_CP", "^[0-9@]{1}[0-9]{4}$"],
	["Dest_Pays", "^[A-Z]{2}$"],
	["Dest_Tel1", "^((00|\\+)33|0)[0-9][0-9]{8}$"],
	["Dest_Tel2", "^((00|\\+)33|0)[0-9][0-9]{8}$"],
	["Dest_Mail", "^[0-9a-zA-Z!#$%&'*+/=?^_`{|}~-]+((\\.[a-zAZ0-9!#$%&'*+/=?^_`{|}~-]+)?)+@(?:[a-zAZ0-9](?:[a-zA-Z0-9-_]*[a-zA-Z0-9])?\\.)+[azA-Z0-9](?:[a-zA-Z0-9\\-]*[a-zA-Z0-9])?$"],
	["Poids", "^[0-9]{3,7}\\.?[0-9]{0,2}$"],
	["Longueur", "^[0-9]{0,3}$"],
	["Taille", "^(XS|S|M|L|XL|3XL)$"],
	["Action", "^(REL|24R|24L|24X|DRI)$"],
	["NbColis", "^[0-9]{1,2}$"],
	["CRT_Valeur", "^0$"],
	["CRT_Devise", "^(|EUR)$"],
	["EXP_Valeur", "^[0-9]{0,7}$"],
	["EXP_Devise", "^(|EUR)$"],
	["COL_Rel_Pays", "^[A-Z]{2}$"],
	["COL_Rel", "^(|[0-9]{6})$"],
	["LIV_Rel_Pays", "^[A-Z]{2}$"],
	["LIV_Rel", "^(|[0-9]{6})$"],
	["TAvisage", "^(|O|N)$"],
	["TReprise", "^(|O|N)$"],
	["Montage", "^(|[0-9]{1,3})$"],
	["TRDV", "^(|O|N)$"],
	["Assurance", "^(|[0-9A-Z]{1})$"],
	["Instructions", "^[0-9A-Z_\\-'., /]{0,31}"],
	["Texte", "^([^<>&']{3,30})(\\(cr\\)[^<>&']{0,30}){0,9}"]
]));

const usePattern = (name) => {
	if(!patterns[name]) throw new Error('Pattern not found : ' + name)

	return new RegExp(patterns[name])
}

exports.usePattern = usePattern;